// <auto-generated />
using System;
using APIClub.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIClub.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20260103174420_AddPropertyIsActivToSocioForNotDeleteHisDirectly")]
    partial class AddPropertyIsActivToSocioForNotDeleteHisDirectly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Alquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAlquiler")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSocio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdSocio");

                    b.ToTable("alquileresArticulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaAlquiler = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Finalizado = false,
                            IdSocio = 1,
                            Observaciones = "Alquiler por 3 días"
                        },
                        new
                        {
                            Id = 2,
                            FechaAlquiler = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Finalizado = true,
                            IdSocio = 2,
                            Observaciones = "Préstamo semanal"
                        },
                        new
                        {
                            Id = 3,
                            FechaAlquiler = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Finalizado = false,
                            IdSocio = 1,
                            Observaciones = "Rehabilitación post operación"
                        },
                        new
                        {
                            Id = 4,
                            FechaAlquiler = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Finalizado = true,
                            IdSocio = 2,
                            Observaciones = "Alquiler viejo ya cerrado"
                        },
                        new
                        {
                            Id = 5,
                            FechaAlquiler = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Finalizado = false,
                            IdSocio = 3,
                            Observaciones = "Alquiler Activo para Test"
                        });
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrecioAlquiler")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Articulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Silla de Ruedas",
                            PrecioAlquiler = 10500
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Andador",
                            PrecioAlquiler = 8000
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Muletas",
                            PrecioAlquiler = 5000
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Bastón",
                            PrecioAlquiler = 4500
                        });
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.ItemAlquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlquilerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticuloId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlquilerId");

                    b.HasIndex("ArticuloId");

                    b.ToTable("ItemALquiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlquilerId = 1,
                            ArticuloId = 1,
                            Cantidad = 1
                        },
                        new
                        {
                            Id = 2,
                            AlquilerId = 1,
                            ArticuloId = 4,
                            Cantidad = 2
                        },
                        new
                        {
                            Id = 3,
                            AlquilerId = 2,
                            ArticuloId = 2,
                            Cantidad = 1
                        },
                        new
                        {
                            Id = 4,
                            AlquilerId = 3,
                            ArticuloId = 3,
                            Cantidad = 2
                        },
                        new
                        {
                            Id = 5,
                            AlquilerId = 3,
                            ArticuloId = 4,
                            Cantidad = 1
                        },
                        new
                        {
                            Id = 6,
                            AlquilerId = 4,
                            ArticuloId = 1,
                            Cantidad = 1
                        },
                        new
                        {
                            Id = 7,
                            AlquilerId = 5,
                            ArticuloId = 1,
                            Cantidad = 1
                        });
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.PagoAlquilerDeArticulos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAlquiler")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Monto")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdAlquiler", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("PagosAlquilerDeArticulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2025,
                            IdAlquiler = 1,
                            Mes = 1,
                            Monto = 10500
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2025,
                            IdAlquiler = 1,
                            Mes = 2,
                            Monto = 10500
                        },
                        new
                        {
                            Id = 3,
                            Anio = 2025,
                            IdAlquiler = 1,
                            Mes = 3,
                            Monto = 10500
                        });
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Cuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormaDePago")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Semestre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SocioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("Cuotas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2024,
                            FechaPago = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormaDePago = 1,
                            Monto = 2500.00m,
                            Semestre = 1,
                            SocioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2024,
                            FechaPago = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormaDePago = 2,
                            Monto = 2500.00m,
                            Semestre = 2,
                            SocioId = 1
                        });
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.MontoCuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoCuotaFija")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MontoCuota");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaActualizacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontoCuotaFija = 2500.00m
                        });
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direcccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaAsociacion")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaDeBaja")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Socios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            Direcccion = "Mitre 100",
                            Dni = "12345678",
                            FechaAsociacion = new DateOnly(2020, 5, 10),
                            IsActivo = true,
                            Localidad = "Rosario",
                            Nombre = "Juan",
                            Telefono = "341-1234567"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Gómez",
                            Direcccion = "San Martín 200",
                            Dni = "87654321",
                            FechaAsociacion = new DateOnly(2021, 3, 15),
                            IsActivo = true,
                            Localidad = "Córdoba",
                            Nombre = "María",
                            Telefono = "341-7654321"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Ruiz",
                            Direcccion = "Belgrano 500",
                            Dni = "11223344",
                            FechaAsociacion = new DateOnly(2022, 1, 10),
                            IsActivo = true,
                            Localidad = "Rosario",
                            Nombre = "Carlos",
                            Telefono = "341-9988776"
                        });
                });

            modelBuilder.Entity("APIClub.Domain.PaymentsOnline.Modelos.PaymentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaExpiracion")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdSocio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Preference_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusDetail")
                        .HasColumnType("TEXT");

                    b.Property<int>("anio")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombreSocio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("semestre")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("usado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PaymentTokens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            FechaExpiracion = new DateOnly(2026, 2, 2),
                            IdSocio = 1,
                            anio = 2025,
                            monto = 2500.00m,
                            nombreSocio = "Juan Pérez",
                            semestre = 1,
                            usado = false
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            FechaExpiracion = new DateOnly(2026, 2, 2),
                            IdSocio = 1,
                            anio = 2025,
                            monto = 2500.00m,
                            nombreSocio = "Juan Pérez",
                            semestre = 2,
                            usado = false
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            FechaExpiracion = new DateOnly(2026, 2, 2),
                            IdSocio = 2,
                            anio = 2025,
                            monto = 2500.00m,
                            nombreSocio = "María Gómez",
                            semestre = 1,
                            usado = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            FechaExpiracion = new DateOnly(2026, 2, 2),
                            IdSocio = 2,
                            anio = 2025,
                            monto = 2500.00m,
                            nombreSocio = "María Gómez",
                            semestre = 2,
                            usado = false
                        });
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.ReservaSalon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAlquiler")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SocioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.HasIndex("SocioId");

                    b.ToTable("ReservasSalones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaAlquiler = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Importe = 5000.00m,
                            SalonId = 1,
                            SocioId = 1,
                            Titulo = "fiesta de 15 cele",
                            TotalPagado = 0.00m
                        },
                        new
                        {
                            Id = 2,
                            FechaAlquiler = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Importe = 7000.00m,
                            SalonId = 2,
                            SocioId = 2,
                            Titulo = "baile abuelos",
                            TotalPagado = 7000.00m
                        });
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Salones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Calle Falsa 123",
                            Name = "Salón Central"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Av. Siempre Viva 742",
                            Name = "Salón Norte"
                        });
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Alquiler", b =>
                {
                    b.HasOne("APIClub.Domain.GestionSocios.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.ItemAlquiler", b =>
                {
                    b.HasOne("APIClub.Domain.AlquilerArticulos.Models.Alquiler", "Alquiler")
                        .WithMany("Items")
                        .HasForeignKey("AlquilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIClub.Domain.AlquilerArticulos.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alquiler");

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.PagoAlquilerDeArticulos", b =>
                {
                    b.HasOne("APIClub.Domain.AlquilerArticulos.Models.Alquiler", "alquiler")
                        .WithMany("HistorialDePagos")
                        .HasForeignKey("IdAlquiler")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("alquiler");
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Cuota", b =>
                {
                    b.HasOne("APIClub.Domain.GestionSocios.Models.Socio", "Socio")
                        .WithMany("HistorialCuotas")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.ReservaSalon", b =>
                {
                    b.HasOne("APIClub.Domain.ReservasSalones.Models.Salon", "Salon")
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIClub.Domain.GestionSocios.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salon");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Alquiler", b =>
                {
                    b.Navigation("HistorialDePagos");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Socio", b =>
                {
                    b.Navigation("HistorialCuotas");
                });
#pragma warning restore 612, 618
        }
    }
}
