events {}

http {
  # Redirige todo HTTP a HTTPS
  server {
    listen 80;
    server_name admin.casadeljubilado.com.ar api.casadeljubilado.com.ar;

    location /.well-known/acme-challenge/ {
      root /var/www/certbot;
    }

    location / {
      return 301 https://$host$request_uri;
    }
  }

  # Servidor HTTPS
  server {
    listen 443 ssl;
    server_name admin.casadeljubilado.com.ar;

    ssl_certificate /etc/letsencrypt/live/admin.casadeljubilado.com.ar/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/admin.casadeljubilado.com.ar/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
      proxy_pass http://frontend:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
      proxy_pass http://api:5000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  server {
    listen 443 ssl;
    server_name api.casadeljubilado.com.ar;

    ssl_certificate /etc/letsencrypt/live/api.casadeljubilado.com.ar/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.casadeljubilado.com.ar/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
      proxy_pass http://frontend:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
      proxy_pass http://api:5000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
