// <auto-generated />
using System;
using APIClub.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIClub.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20260124181139_newMigration")]
    partial class newMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Alquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAlquiler")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSocio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdSocio");

                    b.ToTable("alquileresArticulos");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrecioAlquiler")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.ItemAlquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlquilerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticuloId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlquilerId");

                    b.HasIndex("ArticuloId");

                    b.ToTable("ItemALquiler");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.PagoAlquilerDeArticulos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAlquiler")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Monto")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdAlquiler", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("PagosAlquilerDeArticulos");
                });

            modelBuilder.Entity("APIClub.Domain.Auth.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreUsuario = "admin",
                            PasswordHash = "$2a$11$eiq0ojKVi/ogGtQ33UFfUOOlJrD2TATNOxzQ7xQkpFZZLwqTU.hZa",
                            Rol = 1
                        });
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Cuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormaDePago")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Semestre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SocioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("Cuotas");
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalleEste")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CalleNorte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CalleOeste")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CalleSur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreLote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.MontoCuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoCuotaFija")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MontoCuota");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontoCuotaFija = 5000.00m
                        });
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.RegistroCobrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaCobro")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCobrador")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoCobrado")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreSocio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegistroCobradores");
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direcccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaAsociacion")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaDeBaja")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localidad")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferenciaDePago")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Socios");
                });

            modelBuilder.Entity("APIClub.Domain.PaymentsOnline.Modelos.PaymentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaExpiracion")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdSocio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Preference_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusDetail")
                        .HasColumnType("TEXT");

                    b.Property<int>("anio")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombreSocio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("semestre")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("usado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PaymentTokens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            FechaExpiracion = new DateOnly(2026, 2, 23),
                            IdSocio = 1,
                            anio = 2025,
                            monto = 2500.00m,
                            nombreSocio = "Juan Pérez",
                            semestre = 1,
                            usado = false
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            FechaExpiracion = new DateOnly(2026, 2, 23),
                            IdSocio = 1,
                            anio = 2025,
                            monto = 2500.00m,
                            nombreSocio = "Juan Pérez",
                            semestre = 2,
                            usado = false
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            FechaExpiracion = new DateOnly(2026, 2, 23),
                            IdSocio = 2,
                            anio = 2025,
                            monto = 2500.00m,
                            nombreSocio = "María Gómez",
                            semestre = 1,
                            usado = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            FechaExpiracion = new DateOnly(2026, 2, 23),
                            IdSocio = 2,
                            anio = 2025,
                            monto = 2500.00m,
                            nombreSocio = "María Gómez",
                            semestre = 2,
                            usado = false
                        });
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.PagoReservaSalon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservaSalonId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReservaSalonId");

                    b.ToTable("pagoReservaSalon");
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.ReservaSalon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAlquiler")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SocioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.HasIndex("SocioId");

                    b.ToTable("ReservasSalones");
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Salones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Calle Falsa 123",
                            Name = "Salón chico"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Av. Siempre Viva 742",
                            Name = "Salón grande"
                        });
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Alquiler", b =>
                {
                    b.HasOne("APIClub.Domain.GestionSocios.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.ItemAlquiler", b =>
                {
                    b.HasOne("APIClub.Domain.AlquilerArticulos.Models.Alquiler", "Alquiler")
                        .WithMany("Items")
                        .HasForeignKey("AlquilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIClub.Domain.AlquilerArticulos.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alquiler");

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.PagoAlquilerDeArticulos", b =>
                {
                    b.HasOne("APIClub.Domain.AlquilerArticulos.Models.Alquiler", "alquiler")
                        .WithMany("HistorialDePagos")
                        .HasForeignKey("IdAlquiler")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("alquiler");
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Cuota", b =>
                {
                    b.HasOne("APIClub.Domain.GestionSocios.Models.Socio", "Socio")
                        .WithMany("HistorialCuotas")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Socio", b =>
                {
                    b.HasOne("APIClub.Domain.GestionSocios.Models.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.PagoReservaSalon", b =>
                {
                    b.HasOne("APIClub.Domain.ReservasSalones.Models.ReservaSalon", null)
                        .WithMany("historialPagos")
                        .HasForeignKey("ReservaSalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.ReservaSalon", b =>
                {
                    b.HasOne("APIClub.Domain.ReservasSalones.Models.Salon", "Salon")
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIClub.Domain.GestionSocios.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salon");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Alquiler", b =>
                {
                    b.Navigation("HistorialDePagos");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Socio", b =>
                {
                    b.Navigation("HistorialCuotas");
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.ReservaSalon", b =>
                {
                    b.Navigation("historialPagos");
                });
#pragma warning restore 612, 618
        }
    }
}
