// <auto-generated />
using System;
using APIClub.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIClub.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20260221151538_updateNullabilidadInVarianteViaje")]
    partial class updateNullabilidadInVarianteViaje
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Alquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAlquiler")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("boolean");

                    b.Property<int>("IdSocio")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IdSocio");

                    b.ToTable("alquileresArticulos");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PrecioAlquiler")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.ItemAlquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlquilerId")
                        .HasColumnType("integer");

                    b.Property<int>("ArticuloId")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlquilerId");

                    b.HasIndex("ArticuloId");

                    b.ToTable("ItemALquiler");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.PagoAlquilerDeArticulos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<int>("IdAlquiler")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<int>("Monto")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdAlquiler", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("PagosAlquilerDeArticulos");
                });

            modelBuilder.Entity("APIClub.Domain.Auth.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreUsuario = "admin",
                            PasswordHash = "$2a$11$LDLGC9.fiYAlSuwt6f//Fel7Vf3JxNn.pGJrMW5c2svp1lz4ps022",
                            Rol = 1
                        });
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direcccion")
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("FechaAsociacion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaDeBaja")
                        .HasColumnType("date");

                    b.Property<bool>("IsActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Localidad")
                        .HasColumnType("text");

                    b.Property<int?>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PreferenciaDePago")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Socios");
                });

            modelBuilder.Entity("APIClub.Domain.ModuloGestionCobradores.Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CalleEste")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CalleNorte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CalleOeste")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CalleSur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreLote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("APIClub.Domain.ModuloGestionCobradores.Models.RegistroCobrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("FechaCobro")
                        .HasColumnType("date");

                    b.Property<int>("IdCobrador")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoCobrado")
                        .HasColumnType("numeric");

                    b.Property<string>("NombreSocio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RegistroCobradores");
                });

            modelBuilder.Entity("APIClub.Domain.ModuloGestionCuotas.Models.Cuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FormaDePago")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Semestre")
                        .HasColumnType("integer");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("Cuotas");
                });

            modelBuilder.Entity("APIClub.Domain.ModuloGestionCuotas.Models.MontoCuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("MontoCuotaFija")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MontoCuota");
                });

            modelBuilder.Entity("APIClub.Domain.ModuloGestionViajes.Models.InscriptoViaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MontoPendiente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer");

                    b.Property<int>("VarianteViajeId")
                        .HasColumnType("integer");

                    b.Property<bool>("cancelado")
                        .HasColumnType("boolean");

                    b.Property<decimal>("montoAbonado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.HasIndex("VarianteViajeId");

                    b.ToTable("Inscriptos");
                });

            modelBuilder.Entity("APIClub.Domain.ModuloGestionViajes.Models.VarianteViaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdViaje")
                        .HasColumnType("integer");

                    b.Property<string>("NombreVariante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("Regimen")
                        .HasColumnType("integer");

                    b.Property<string>("TipoDeButaca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("ValorSeña")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorViaje")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdViaje");

                    b.ToTable("VariantesViaje");
                });

            modelBuilder.Entity("APIClub.Domain.ModuloGestionViajes.Models.Viaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Dias")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fechasalida")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Noches")
                        .HasColumnType("integer");

                    b.Property<decimal>("PorcentajeComision")
                        .HasColumnType("numeric");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("ValorBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VentasParaLiberado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Viajes");
                });

            modelBuilder.Entity("APIClub.Domain.PaymentsOnline.Modelos.PaymentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("FechaExpiracion")
                        .HasColumnType("date");

                    b.Property<int>("IdSocio")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("text");

                    b.Property<string>("Preference_Id")
                        .HasColumnType("text");

                    b.Property<string>("StatusDetail")
                        .HasColumnType("text");

                    b.Property<int>("anio")
                        .HasColumnType("integer");

                    b.Property<decimal>("monto")
                        .HasColumnType("numeric");

                    b.Property<string>("nombreSocio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("semestre")
                        .HasColumnType("integer");

                    b.Property<bool>("usado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PaymentTokens");
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.PagoReservaSalon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ReservaSalonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReservaSalonId");

                    b.ToTable("pagoReservaSalon");
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.ReservaSalon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAlquiler")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.HasIndex("SocioId");

                    b.ToTable("ReservasSalones");
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Salones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Calle Falsa 123",
                            Name = "Salón chico"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Av. Siempre Viva 742",
                            Name = "Salón grande"
                        });
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Alquiler", b =>
                {
                    b.HasOne("APIClub.Domain.GestionSocios.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.ItemAlquiler", b =>
                {
                    b.HasOne("APIClub.Domain.AlquilerArticulos.Models.Alquiler", "Alquiler")
                        .WithMany("Items")
                        .HasForeignKey("AlquilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIClub.Domain.AlquilerArticulos.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alquiler");

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.PagoAlquilerDeArticulos", b =>
                {
                    b.HasOne("APIClub.Domain.AlquilerArticulos.Models.Alquiler", "alquiler")
                        .WithMany("HistorialDePagos")
                        .HasForeignKey("IdAlquiler")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("alquiler");
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Socio", b =>
                {
                    b.HasOne("APIClub.Domain.ModuloGestionCobradores.Models.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("APIClub.Domain.ModuloGestionCuotas.Models.Cuota", b =>
                {
                    b.HasOne("APIClub.Domain.GestionSocios.Models.Socio", "Socio")
                        .WithMany("HistorialCuotas")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("APIClub.Domain.ModuloGestionViajes.Models.InscriptoViaje", b =>
                {
                    b.HasOne("APIClub.Domain.GestionSocios.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIClub.Domain.ModuloGestionViajes.Models.VarianteViaje", "Variante")
                        .WithMany("Inscriptos")
                        .HasForeignKey("VarianteViajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Socio");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("APIClub.Domain.ModuloGestionViajes.Models.VarianteViaje", b =>
                {
                    b.HasOne("APIClub.Domain.ModuloGestionViajes.Models.Viaje", "Viaje")
                        .WithMany("Variantes")
                        .HasForeignKey("IdViaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.PagoReservaSalon", b =>
                {
                    b.HasOne("APIClub.Domain.ReservasSalones.Models.ReservaSalon", null)
                        .WithMany("historialPagos")
                        .HasForeignKey("ReservaSalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.ReservaSalon", b =>
                {
                    b.HasOne("APIClub.Domain.ReservasSalones.Models.Salon", "Salon")
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIClub.Domain.GestionSocios.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salon");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Alquiler", b =>
                {
                    b.Navigation("HistorialDePagos");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Socio", b =>
                {
                    b.Navigation("HistorialCuotas");
                });

            modelBuilder.Entity("APIClub.Domain.ModuloGestionViajes.Models.VarianteViaje", b =>
                {
                    b.Navigation("Inscriptos");
                });

            modelBuilder.Entity("APIClub.Domain.ModuloGestionViajes.Models.Viaje", b =>
                {
                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.ReservaSalon", b =>
                {
                    b.Navigation("historialPagos");
                });
#pragma warning restore 612, 618
        }
    }
}
