// <auto-generated />
using System;
using APIClub.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIClub.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    partial class AppDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Alquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAlquiler")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("boolean");

                    b.Property<int>("IdSocio")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IdSocio");

                    b.ToTable("alquileresArticulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaAlquiler = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Finalizado = false,
                            IdSocio = 1,
                            Observaciones = "Alquiler por 3 días"
                        },
                        new
                        {
                            Id = 2,
                            FechaAlquiler = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Finalizado = true,
                            IdSocio = 2,
                            Observaciones = "Préstamo semanal"
                        },
                        new
                        {
                            Id = 3,
                            FechaAlquiler = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Finalizado = false,
                            IdSocio = 1,
                            Observaciones = "Rehabilitación post operación"
                        },
                        new
                        {
                            Id = 4,
                            FechaAlquiler = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Finalizado = true,
                            IdSocio = 2,
                            Observaciones = "Alquiler viejo ya cerrado"
                        },
                        new
                        {
                            Id = 5,
                            FechaAlquiler = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Finalizado = false,
                            IdSocio = 3,
                            Observaciones = "Alquiler Activo para Test"
                        });
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PrecioAlquiler")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Articulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Silla de Ruedas",
                            PrecioAlquiler = 10500m
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Andador",
                            PrecioAlquiler = 8000m
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Muletas",
                            PrecioAlquiler = 5000m
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Bastón",
                            PrecioAlquiler = 4500m
                        });
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.ItemAlquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlquilerId")
                        .HasColumnType("integer");

                    b.Property<int>("ArticuloId")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlquilerId");

                    b.HasIndex("ArticuloId");

                    b.ToTable("ItemALquiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlquilerId = 1,
                            ArticuloId = 1,
                            Cantidad = 1
                        },
                        new
                        {
                            Id = 2,
                            AlquilerId = 1,
                            ArticuloId = 4,
                            Cantidad = 2
                        },
                        new
                        {
                            Id = 3,
                            AlquilerId = 2,
                            ArticuloId = 2,
                            Cantidad = 1
                        },
                        new
                        {
                            Id = 4,
                            AlquilerId = 3,
                            ArticuloId = 3,
                            Cantidad = 2
                        },
                        new
                        {
                            Id = 5,
                            AlquilerId = 3,
                            ArticuloId = 4,
                            Cantidad = 1
                        },
                        new
                        {
                            Id = 6,
                            AlquilerId = 4,
                            ArticuloId = 1,
                            Cantidad = 1
                        },
                        new
                        {
                            Id = 7,
                            AlquilerId = 5,
                            ArticuloId = 1,
                            Cantidad = 1
                        });
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.PagoAlquilerDeArticulos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<int>("IdAlquiler")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<int>("Monto")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdAlquiler", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("PagosAlquilerDeArticulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2025,
                            IdAlquiler = 1,
                            Mes = 1,
                            Monto = 10500
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2025,
                            IdAlquiler = 1,
                            Mes = 2,
                            Monto = 10500
                        },
                        new
                        {
                            Id = 3,
                            Anio = 2025,
                            IdAlquiler = 1,
                            Mes = 3,
                            Monto = 10500
                        });
                });

            modelBuilder.Entity("APIClub.Domain.Auth.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreUsuario = "admin",
                            PasswordHash = "$2a$11$M2Fjq3K7LEm/QZJJRaywi.1nwsRdDQKM1jvtyzKiRjZCqLT6Ti0dW",
                            Rol = 1
                        });
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Cuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FormaDePago")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Semestre")
                        .HasColumnType("integer");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("Cuotas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2024,
                            FechaPago = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormaDePago = 1,
                            Monto = 2500.00m,
                            Semestre = 1,
                            SocioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2024,
                            FechaPago = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormaDePago = 2,
                            Monto = 2500.00m,
                            Semestre = 2,
                            SocioId = 1
                        });
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CalleEste")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CalleNorte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CalleOeste")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CalleSur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreLote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalleEste = "Belgrano",
                            CalleNorte = "Mitre",
                            CalleOeste = "Urquiza",
                            CalleSur = "San Martín",
                            NombreLote = "Lote A"
                        },
                        new
                        {
                            Id = 2,
                            CalleEste = "Salta",
                            CalleNorte = "Av. Pellegrini",
                            CalleOeste = "Jujuy",
                            CalleSur = "Bv. Oroño",
                            NombreLote = "Lote B"
                        },
                        new
                        {
                            Id = 3,
                            CalleEste = "Lavalle",
                            CalleNorte = "Av. Corrientes",
                            CalleOeste = "Sarmiento",
                            CalleSur = "Florida",
                            NombreLote = "Lote C"
                        });
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.MontoCuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("MontoCuotaFija")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MontoCuota");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaActualizacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MontoCuotaFija = 2500.00m
                        });
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direcccion")
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("FechaAsociacion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaDeBaja")
                        .HasColumnType("date");

                    b.Property<bool>("IsActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Localidad")
                        .HasColumnType("text");

                    b.Property<int?>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PreferenciaDePago")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Socios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            Direcccion = "Mitre 100",
                            Dni = "12345678",
                            FechaAsociacion = new DateOnly(2020, 5, 10),
                            IsActivo = true,
                            Localidad = "Rosario",
                            LoteId = 1,
                            Nombre = "Juan",
                            PreferenciaDePago = 0,
                            Telefono = "341-1234567"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Gómez",
                            Direcccion = "San Martín 200",
                            Dni = "87654321",
                            FechaAsociacion = new DateOnly(2021, 3, 15),
                            IsActivo = true,
                            Localidad = "Córdoba",
                            LoteId = 2,
                            Nombre = "María",
                            PreferenciaDePago = 2,
                            Telefono = "341-7654321"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Ruiz",
                            Direcccion = "Belgrano 500",
                            Dni = "11223344",
                            FechaAsociacion = new DateOnly(2022, 1, 10),
                            IsActivo = true,
                            Localidad = "Rosario",
                            LoteId = 3,
                            Nombre = "Carlos",
                            PreferenciaDePago = 1,
                            Telefono = "341-9988776"
                        });
                });

            modelBuilder.Entity("APIClub.Domain.PaymentsOnline.Modelos.PaymentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("FechaExpiracion")
                        .HasColumnType("date");

                    b.Property<int>("IdSocio")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("text");

                    b.Property<string>("Preference_Id")
                        .HasColumnType("text");

                    b.Property<string>("StatusDetail")
                        .HasColumnType("text");

                    b.Property<int>("anio")
                        .HasColumnType("integer");

                    b.Property<decimal>("monto")
                        .HasColumnType("numeric");

                    b.Property<string>("nombreSocio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("semestre")
                        .HasColumnType("integer");

                    b.Property<bool>("usado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PaymentTokens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            FechaExpiracion = new DateOnly(2026, 2, 19),
                            IdSocio = 1,
                            anio = 2025,
                            monto = 2500.00m,
                            nombreSocio = "Juan Pérez",
                            semestre = 1,
                            usado = false
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            FechaExpiracion = new DateOnly(2026, 2, 19),
                            IdSocio = 1,
                            anio = 2025,
                            monto = 2500.00m,
                            nombreSocio = "Juan Pérez",
                            semestre = 2,
                            usado = false
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            FechaExpiracion = new DateOnly(2026, 2, 19),
                            IdSocio = 2,
                            anio = 2025,
                            monto = 2500.00m,
                            nombreSocio = "María Gómez",
                            semestre = 1,
                            usado = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            FechaExpiracion = new DateOnly(2026, 2, 19),
                            IdSocio = 2,
                            anio = 2025,
                            monto = 2500.00m,
                            nombreSocio = "María Gómez",
                            semestre = 2,
                            usado = false
                        });
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.PagoReservaSalon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ReservaSalonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReservaSalonId");

                    b.ToTable("pagoReservaSalon");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaPago = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservaSalonId = 1,
                            monto = 2000.00m
                        },
                        new
                        {
                            Id = 2,
                            FechaPago = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservaSalonId = 1,
                            monto = 2000.00m
                        },
                        new
                        {
                            Id = 3,
                            FechaPago = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservaSalonId = 2,
                            monto = 3000.00m
                        },
                        new
                        {
                            Id = 4,
                            FechaPago = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservaSalonId = 2,
                            monto = 2000.00m
                        },
                        new
                        {
                            Id = 5,
                            FechaPago = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservaSalonId = 2,
                            monto = 2000.00m
                        },
                        new
                        {
                            Id = 6,
                            FechaPago = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservaSalonId = 4,
                            monto = 3000.00m
                        });
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.ReservaSalon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAlquiler")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.HasIndex("SocioId");

                    b.ToTable("ReservasSalones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaAlquiler = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Importe = 5000.00m,
                            IsCancelled = false,
                            SalonId = 1,
                            SocioId = 1,
                            Titulo = "fiesta de 15 cele",
                            TotalPagado = 4000.00m
                        },
                        new
                        {
                            Id = 2,
                            FechaAlquiler = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Importe = 7000.00m,
                            IsCancelled = false,
                            SalonId = 2,
                            SocioId = 2,
                            Titulo = "baile abuelos",
                            TotalPagado = 7000.00m
                        },
                        new
                        {
                            Id = 3,
                            FechaAlquiler = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Importe = 6000.00m,
                            IsCancelled = false,
                            SalonId = 1,
                            SocioId = 3,
                            Titulo = "Cumpleaños de Carlos",
                            TotalPagado = 0.00m
                        },
                        new
                        {
                            Id = 4,
                            FechaAlquiler = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Importe = 8000.00m,
                            IsCancelled = false,
                            SalonId = 2,
                            SocioId = 1,
                            Titulo = "Reunión Familiar",
                            TotalPagado = 3000.00m
                        });
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Salones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Calle Falsa 123",
                            Name = "Salón Central"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Av. Siempre Viva 742",
                            Name = "Salón Norte"
                        });
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Alquiler", b =>
                {
                    b.HasOne("APIClub.Domain.GestionSocios.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("IdSocio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.ItemAlquiler", b =>
                {
                    b.HasOne("APIClub.Domain.AlquilerArticulos.Models.Alquiler", "Alquiler")
                        .WithMany("Items")
                        .HasForeignKey("AlquilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIClub.Domain.AlquilerArticulos.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alquiler");

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.PagoAlquilerDeArticulos", b =>
                {
                    b.HasOne("APIClub.Domain.AlquilerArticulos.Models.Alquiler", "alquiler")
                        .WithMany("HistorialDePagos")
                        .HasForeignKey("IdAlquiler")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("alquiler");
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Cuota", b =>
                {
                    b.HasOne("APIClub.Domain.GestionSocios.Models.Socio", "Socio")
                        .WithMany("HistorialCuotas")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Socio", b =>
                {
                    b.HasOne("APIClub.Domain.GestionSocios.Models.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.PagoReservaSalon", b =>
                {
                    b.HasOne("APIClub.Domain.ReservasSalones.Models.ReservaSalon", null)
                        .WithMany("historialPagos")
                        .HasForeignKey("ReservaSalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.ReservaSalon", b =>
                {
                    b.HasOne("APIClub.Domain.ReservasSalones.Models.Salon", "Salon")
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIClub.Domain.GestionSocios.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salon");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("APIClub.Domain.AlquilerArticulos.Models.Alquiler", b =>
                {
                    b.Navigation("HistorialDePagos");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("APIClub.Domain.GestionSocios.Models.Socio", b =>
                {
                    b.Navigation("HistorialCuotas");
                });

            modelBuilder.Entity("APIClub.Domain.ReservasSalones.Models.ReservaSalon", b =>
                {
                    b.Navigation("historialPagos");
                });
#pragma warning restore 612, 618
        }
    }
}
